# fly.toml app configuration file generated for datahivebe on 2023-04-25T14:29:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datahivebe"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[deploy]
  strategy = "immediate"
